import fs from 'fs';
import path from 'path';

interface IR {
  id: string;
  nodes: Record<
    string,
    { id: string; type: string; next?: string; end?: boolean }
  >;
}

export function generateTemporalArtifacts(ir: IR, outDir: string) {
  const base = path.resolve(outDir, 'temporal');
  const wfDir = path.join(base, 'workflows');
  const actDir = path.join(base, 'activities');
  fs.mkdirSync(wfDir, { recursive: true });
  fs.mkdirSync(actDir, { recursive: true });

  const wfFile = path.join(wfDir, `${ir.id}.ts`);
  const wfSrc = `// Auto-generated by Orkestr (Temporal target)
export async function ${camel(ir.id)}Workflow() {
  // TODO: Implement using Temporal SDK
  // States:
${Object.values(ir.nodes)
  .map((n) => `  // - ${n.id} (${n.type})`)
  .join('\n')}
}
`;
  fs.writeFileSync(wfFile, wfSrc);

  for (const n of Object.values(ir.nodes)) {
    if (n.type === 'task') {
      const f = path.join(actDir, `${n.id}.ts`);
      const src = `// Auto-generated activity for ${n.id}
export async function ${camel(n.id)}Activity(input: unknown): Promise<unknown> {
  // TODO: implement
  return input;
}
`;
      fs.writeFileSync(f, src);
    }
  }

  const diagFile = path.join(base, 'orkestr-target.json');
  fs.writeFileSync(
    diagFile,
    JSON.stringify({ target: 'temporal', workflow: ir.id, notes: [] }, null, 2),
  );
  return { outDir: base };
}

function camel(s: string) {
  return s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}
